#!/bin/bash

# Get $CURRENT
CURRENT=$(realpath $(pwd))

# Get $RGIT_ROOT
RGIT_ROOT=$(dirname $(realpath $0))
cd $RGIT_ROOT

# Get $RGIT_CMD
RGIT_CMD=$1
shift

# Check $RGIT_CMD
if [ "$RGIT_CMD" = "" ];then
    RGIT_CMD='help'
fi
if [[ "$RGIT_CMD" = "--help" || "$RGIT_CMD" = "-h" ]];then
    RGIT_CMD='help'
fi
if [ ! -f "bin/$RGIT_CMD.sh" ];then
    echo "rgit: '$RGIT_CMD' is not a rgit command. See '${0##*/} --help'.">&2
    exit 1
fi

# Load lib/*
for LIB in $(ls -1 lib)
do
    . lib/$LIB
done

# Run $RGIT_CMD
. bin/$RGIT_CMD.sh $@
